name: node
on:
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        shell: bash

    steps:

      - name: Descargar Repositorio
        uses: actions/checkout@v4

